import xarray as xr
from .pac_man import which as which
from .tools import cwd as cwd, execute_cmd as execute_cmd, mv as mv, n_cpu as n_cpu, rm as rm, symlink as symlink, tmp as tmp, type_cast as type_cast
from _typeshed import Incomplete
from os import PathLike
from pathlib import Path
from typing import Any, Literal

class CDONotFoundError(FileNotFoundError): ...

class CDO:
    cdo_path: Incomplete
    tmp_dir: Incomplete
    cwd: Incomplete
    cwd_tmp: Incomplete
    def __init__(self) -> None: ...
    def help(self) -> None: ...
    def run(self, cmd: list[str] = None) -> Any: ...
    def griddes(self, infile: Path | PathLike) -> dict: ...
    def mergetime(self, infiles: list[PathLike], outfile: Path | PathLike, *, as_xarray: bool = False, delete_input: bool = False): ...
    def remapdis(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, resolution: float = 0.25, bbox: tuple[float, float, float, float] = None, as_xarray: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...
    def remapnn(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, resolution: float = 0.25, bbox: tuple[float, float, float, float] = None, as_xarray: bool = False, extrapolate: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...
    def remapcon(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, resolution: float = 0.25, bbox: tuple[float, float, float, float] = None, as_xarray: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...
    def remapbil(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, resolution: float = 0.25, bbox: tuple[float, float, float, float] = None, as_xarray: bool = False, extrapolate: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...
    def remapbic(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, resolution: float = 0.25, bbox: tuple[float, float, float, float] = None, as_xarray: bool = False, extrapolate: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...
    def remaplaf(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, resolution: float = 0.25, bbox: tuple[float, float, float, float] = None, as_xarray: bool = False, extrapolate: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...
    def remapeta(self, vct: Path | PathLike, oro: Path | PathLike, infile: Path | PathLike, outfile: Path | PathLike = None, remapeta_ptop: float = None): ...
    def vlist(self, infile: Path | PathLike) -> str: ...
    def info(self, infile: Path | PathLike, operator: Literal['info', 'infon', 'sinfo', 'sinfon'] = 'sinfon') -> str: ...
    def showinfo(self, infile: Path | PathLike) -> str: ...
    def ninfo(self, infile: Path | PathLike, operator: Literal['npar', 'nlevel', 'nyear', 'nmon', 'ndate', 'ntime', 'ngridpoints', 'ngrids'] = None) -> str: ...
    def split(self, infile: Path | PathLike, outdir: Path | PathLike = None, obase: str = None, operator: Literal['splitcode', 'splitparam', 'splitname', 'splitlevel', 'splitgrid', 'splitzaxis', 'splittabnum'] = None) -> list[str]: ...
    def to_nc4(self, infile: Path | PathLike, outfile: Path | PathLike = None, *, as_xarray: bool = False) -> None: ...
    def get_vert_coords(self, infile: Path | PathLike) -> str: ...
    def netcdf_to_grib(self, infile: Path | PathLike, outfile: Path | PathLike = None) -> str | PathLike: ...
    def grib_to_netcdf(self, infile: Path | PathLike, outdir: Path | PathLike = None, merge: bool = True, *, p_levels: list[float] = None, h_levels: list[float] = None, extrapolate: bool = False, spectral_operator: Literal['sp2gp', 'gp2sp', 'sp2sp', 'dv2ps', 'dv2uv', 'uv2dv'] = None, p_type: Literal['linear', 'quadratic', 'cubic'] = None, trunc: bool = False) -> xr.DataArray | xr.Dataset | str | PathLike: ...

cdo: CDO
