import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
from os import PathLike
from typing import Literal

def get_cbar_axes(*, fig: plt.Figure = None, axes: plt.Axes = None, subplots: bool = False, orientation: Literal['vertical', 'horizontal'] = 'vertical', pad: float = 0.04) -> plt.Axes: ...
def make_lon_cyclic(obj: xr.DataArray, longitude: str = 'lon'): ...
def plot_p_values(ax: plt.Axes, data: xr.DataArray, level: float = 0.05, color: str = 'grey', alpha: float = 1, s: float = 1): ...
def cartplot(data: xr.DataArray, *, x: str = None, y: str = None, projection: Literal['PlateCarree', 'Mercator', 'Robinson', 'Mollweide', 'Orthographic', 'LambertConformal', 'AlbersEqualArea', 'Stereographic', 'NorthPolarStereo', 'SouthPolarStereo'] = 'PlateCarree', central_longitude: float = None, central_latitude: float = None, global_extent: bool = False, figsize: tuple[float, float] = None, plot_type: Literal['default', 'pcolormesh', 'contourf', 'contour', 'imshow'] = 'default', cmap: str | mcolors.Colormap = None, vmin: float = None, vmax: float = None, levels: int | list = None, robust: bool = False, orientation: Literal['vertical', 'horizontal'] = 'vertical', add_colorbar: bool = True, drawedges: bool = False, cbar_label: str = None, gridlines: bool = False, coastlines: bool = True, borders: bool = True, states: bool = True, ocean: bool = True, land: bool = True, edgecolor: str = 'face', **kwargs): ...
def animate(data: xr.DataArray, dim: str = 'time', *, indices: tuple | list | np.ndarray = None, outfile: PathLike = None, quality: Literal['low', 'medium', 'high'] = 'medium', fps: int = 10, parallel: bool = True, x: str = None, y: str = None, projection: Literal['PlateCarree', 'Mercator', 'Robinson', 'Mollweide', 'Orthographic', 'LambertConformal', 'AlbersEqualArea', 'Stereographic', 'NorthPolarStereo', 'SouthPolarStereo'] = 'PlateCarree', global_extent: bool = False, figsize: tuple[float, float] = None, central_longitude: float = None, central_latitude: float = None, plot_type: Literal['default', 'pcolormesh', 'contourf', 'contour', 'imshow'] = 'default', cmap: str | mcolors.Colormap = None, vmin: float = None, vmax: float = None, levels: int | list = None, robust: bool = False, transform: bool = None, orientation: Literal['vertical', 'horizontal'] = 'vertical', add_colorbar: bool = True, drawedges: bool = False, cbar_label: str = None, gridlines: bool = False, coastlines: bool = True, borders: bool = True, states: bool = True, ocean: bool = True, land: bool = True, facecolor: str = '#d3d3d3', edgecolor: str = 'face', **kwargs): ...

class CartPlotAccessor:
    def __init__(self, xarray_obj) -> None: ...
    def plot(self, *args, **kwargs) -> None: ...

class CartAnimateAccessor:
    def __init__(self, xarray_obj) -> None: ...
    def plots(self, *args, **kwargs) -> None: ...
