from .logs import *
import numpy as np
import pandas as pd
import xarray as xr
from pathlib import Path
from typing import Any, Callable, Literal, Mapping

host: str
user: str
home: Path
tmp: Path
n_cpu: int
SCRIPT_DIR: Path
CURRENT_DASK_CLUSTER: Any
CURRENT_DASK_CLIENT: Any

class ConfigMap(dict):
    __getattr__: Any
    __setattr__: Any
    __delattr__: Any

def cwd() -> None: ...
def cleanup() -> None: ...
def execute_cmd(cmd: list[str]): ...
def type_cast(x, use_numpy: bool = False): ...
def timeit(func) -> None: ...
def mkdir(path: Path): ...
def get_func_signature(func) -> None: ...
def file_type(file_path: Path) -> str: ...
def symlink(src: Path, dst: Path): ...
def rm(arg: Path | list[Path]): ...
def cp(src: Path, dst: Path): ...
def mv(src: Path, dst: Path): ...
def land_sea_mask(obj: xr.DataArray | xr.Dataset, *, keep: Literal['land', 'ocean'] = None, mask_file: Literal['cartopy', 'era5'] = 'era5') -> xr.DataArray | xr.Dataset: ...
def get_local_solar_time(data: xr.Dataset): ...
def get_UTC_offset(obj: int | float | np.ndarray | xr.DataArray | xr.Dataset, *, name: Literal['lon', 'longitude', 'x'] = 'lon') -> int | float | np.ndarray | xr.DataArray | xr.Dataset: ...
def chunk_by_dims(obj: xr.DataArray | xr.Dataset, dim: str, N: int) -> dict[str, xr.DataArray | xr.Dataset]: ...
def chunk_longitudes(obj: xr.DataArray | xr.Dataset, *, lon: str = 'lon', deg: int = 15) -> dict[str, xr.DataArray | xr.Dataset]: ...
def chunk_by_timezones(obj: xr.DataArray | xr.Dataset) -> dict[str, xr.DataArray | xr.Dataset]: ...
def tz_apply_func(func: Callable, obj: xr.DataArray | xr.Dataset, multiprocess: bool = True, kwargs: Mapping | None = None) -> xr.DataArray | xr.Dataset: ...
def infer_time_frequency(times: pd.Series | np.ndarray | xr.DataArray) -> tuple[str, tuple[int, int], tuple[int, int], tuple[int, int]]: ...
def interp_data(obj: xr.DataArray | xr.Dataset, resolution: float = 0.25, *, x: str = 'lon', y: str = 'lat', method: Literal['linear', 'nearest', 'cubic'] = 'linear', bbox: tuple[float, float, float, float] = None) -> xr.DataArray | xr.Dataset: ...
def get_spatiotemporal_info(obj: xr.DataArray | xr.Dataset) -> dict: ...
def close_dask() -> None: ...
def setup_dask(*, workers: int = ..., threads_per_worker: int = 1, processes: bool = True, filter_warnings: bool = True): ...
