import numpy as np
import pandas as pd
import xarray as xr
from typing import Literal

def mk_trend_test(array: np.ndarray, scale: float = 1) -> np.ndarray: ...
def calc_trends(data: pd.DataFrame | xr.DataArray | xr.Dataset, along: str = None, *, scale: float = 1, use_dask: bool = True, dask_scheduler: Literal['threads', 'processes'] = 'threads') -> pd.DataFrame | xr.Dataset: ...
def calc_signicance(a: xr.DataArray | xr.Dataset, b: xr.DataArray | xr.Dataset, along: str, *, data_var: str = None, level: float = 0.05) -> xr.Dataset: ...
def polyfit(data, data_var, along, scale: int = 1): ...
