import matplotlib.colors as mcolors
import numpy as np
import xarray as xr
from .plot import animate as animate, cartplot as cartplot, make_cyclic as make_cyclic
from pathlib import Path
from typing import Literal

PathLike = str | Path

class GeoDataArray(xr.DataArray):
    def add_cyclic_point(self, dim: str = 'lon') -> GeoDataArray: ...
    def cartplot(self, x: str = None, y: str = None, projection: Literal['PlateCarree', 'Mercator', 'Robinson', 'Mollweide', 'Orthographic', 'LambertConformal', 'AlbersEqualArea', 'Stereographic', 'NorthPolarStereo', 'SouthPolarStereo'] = 'PlateCarree', central_longitude: float = None, central_latitude: float = None, global_extent: bool = False, figsize: tuple[float, float] = None, plot_type: Literal['default', 'pcolormesh', 'contourf', 'contour', 'imshow'] = 'default', cmap: str | mcolors.Colormap = None, vmin: float = None, vmax: float = None, levels: int | list = None, extend: str = None, robust: bool = False, orientation: Literal['vertical', 'horizontal'] = 'vertical', add_colorbar: bool = True, drawedges: bool = False, cbar_label: str = None, gridlines: bool = False, coastlines: bool = True, borders: bool = True, states: bool = True, ocean: bool = True, land: bool = True, edgecolor: str = 'face', **kwargs): ...
    def animate(self, dim: str = 'time', *, indices: tuple | list | np.ndarray = None, outfile: PathLike = None, quality: Literal['low', 'medium', 'high'] = 'medium', fps: int = 10, parallel: bool = True, x: str = None, y: str = None, projection: Literal['PlateCarree', 'Mercator', 'Robinson', 'Mollweide', 'Orthographic', 'LambertConformal', 'AlbersEqualArea', 'Stereographic', 'NorthPolarStereo', 'SouthPolarStereo'] = 'PlateCarree', global_extent: bool = False, figsize: tuple[float, float] = None, central_longitude: float = None, central_latitude: float = None, plot_type: Literal['default', 'pcolormesh', 'contourf', 'contour', 'imshow'] = 'default', cmap: str | mcolors.Colormap = None, vmin: float = None, vmax: float = None, levels: int | list = None, extend: str = None, robust: bool = False, orientation: Literal['vertical', 'horizontal'] = 'vertical', add_colorbar: bool = True, drawedges: bool = False, cbar_label: str = None, gridlines: bool = False, coastlines: bool = True, borders: bool = True, states: bool = True, ocean: bool = True, land: bool = True, edgecolor: str = 'face', **kwargs) -> None: ...

class CartPlotAccessor:
    def __init__(self, xarray_obj) -> None: ...
    def plot(self, *args, **kwargs): ...
    def animate(self, *args, **kwargs): ...
